import { connectDatabase, disconnectDatabase } from '../config/database.js';
import { GameItemDef } from '../models/GameItemDef.js';

const ITEMS = [
  // ── Buildings ────────────────────────────────────────────────────────
  {
    itemType: 'house',
    label: 'House',
    emoji: '🏠',
    color: '#D4A574',
    category: 'building',
    placeable: true,
    cols: 6,
    rows: 5,
    interactAction: { type: 'open_scene', payload: 'house' },
    sortOrder: 1,
  },
  {
    itemType: 'cooking_pot',
    label: 'Cooking Pot',
    emoji: '🍳',
    color: '#8B7355',
    category: 'building',
    placeable: true,
    cols: 2,
    rows: 2,
    interactAction: { type: 'open_modal', payload: 'cooking' },
    sortOrder: 2,
  },
  {
    itemType: 'workbench',
    label: 'Workbench',
    emoji: '🔨',
    color: '#6D4C41',
    category: 'building',
    placeable: true,
    cols: 2,
    rows: 2,
    interactAction: { type: 'open_modal', payload: 'crafting' },
    buyable: true,
    gemPrice: 75,
    sortOrder: 3,
  },
  {
    itemType: 'sell_box',
    label: 'Sell Box',
    emoji: '📦',
    color: '#8D6E63',
    category: 'building',
    placeable: true,
    cols: 2,
    rows: 2,
    interactAction: { type: 'open_modal', payload: 'sell_box' },
    sellable: false,
    sortOrder: 4,
  },
  {
    itemType: 'mail_box',
    label: 'Mailbox',
    emoji: '📬',
    color: '#5D4037',
    category: 'building',
    placeable: true,
    cols: 2,
    rows: 2,
    interactAction: { type: 'open_modal', payload: 'mail_box' },
    sellable: false,
    sortOrder: 5,
  },

  // ── Materials ────────────────────────────────────────────────────────
  {
    itemType: 'wood',
    label: 'Wood',
    emoji: '🪵',
    color: '#8D6E63',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    buyable: true,
    gemPrice: 10,
    sortOrder: 12,
  },
  {
    itemType: 'stone',
    label: 'Stone',
    emoji: '🪨',
    color: '#9E9E9E',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    buyable: true,
    gemPrice: 15,
    sortOrder: 13,
  },
  {
    itemType: 'iron_ore',
    label: 'Iron Ore',
    emoji: '⛏️',
    color: '#78909C',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 14,
  },
  {
    itemType: 'scrap',
    label: 'Scrap',
    emoji: '🗑️',
    color: '#607D8B',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 15,
  },
  {
    itemType: 'wooden_plank',
    label: 'Wooden Plank',
    emoji: '📐',
    color: '#A1887F',
    category: 'decoration',
    placeable: true,
    cols: 1,
    rows: 1,
    sortOrder: 23,
  },

  // ── Soil ─────────────────────────────────────────────────────────────
  {
    itemType: 'soil',
    label: 'Soil',
    emoji: '🟫',
    color: '#8B5E3C',
    category: 'decoration',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 0,
  },

  // ── Seeds ────────────────────────────────────────────────────────────
  {
    itemType: 'wheat_seed',
    label: 'Wheat Seed',
    emoji: '🌱',
    color: '#A8D860',
    category: 'seed',
    placeable: true,
    cols: 1,
    rows: 1,
    growthMs: 30_000,
    harvestYield: [
      { itemType: 'wheat_seed', qty: 2 },
      { itemType: 'wheat', qty: 1 },
    ],
    sortOrder: 10,
  },

  // ── Ingredients ──────────────────────────────────────────────────────
  {
    itemType: 'wheat',
    label: 'Wheat',
    emoji: '🌾',
    color: '#E8D44D',
    category: 'ingredient',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 11,
  },

  // ── Decorations ──────────────────────────────────────────────────────
  {
    itemType: 'fence',
    label: 'Fence',
    emoji: '🪵',
    color: '#C4A882',
    category: 'decoration',
    placeable: true,
    cols: 1,
    rows: 1,
    sortOrder: 20,
  },
  {
    itemType: 'rock',
    label: 'Rock',
    emoji: '🪨',
    color: '#9E9E9E',
    category: 'decoration',
    placeable: true,
    cols: 1,
    rows: 1,
    sortOrder: 21,
  },
  {
    itemType: 'pet_bed',
    label: 'Pet Bed',
    emoji: '🛏️',
    color: '#C4A882',
    category: 'decoration',
    subCategory: 'pet_bed',
    placeable: true,
    cols: 2,
    rows: 2,
    buyable: true,
    gemPrice: 50,
    sortOrder: 22,
  },
  {
    itemType: 'fossil_hole',
    label: 'Fossil Hole',
    emoji: '🕳️',
    color: '#6D4C41',
    category: 'decoration',
    subCategory: 'dig_hole',
    placeable: true,
    cols: 1,
    rows: 1,
    sortOrder: 24,
  },

  // ── Scenery (non-acquirable, admin-editable images) ──────────────
  {
    itemType: 'scenery_fence_h',
    label: 'Fence (Horizontal)',
    emoji: '🪵',
    color: '#A0845C',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 100,
  },
  {
    itemType: 'scenery_fence_v',
    label: 'Fence (Vertical)',
    emoji: '🪵',
    color: '#A0845C',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 101,
  },
  {
    itemType: 'scenery_fence_corner',
    label: 'Fence (Corner)',
    emoji: '🪵',
    color: '#A0845C',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 102,
  },
  {
    itemType: 'scenery_tree_oak',
    label: 'Oak Tree',
    emoji: '🌳',
    color: '#2E7D32',
    category: 'scenery',
    placeable: false,
    cols: 2,
    rows: 3,
    sortOrder: 110,
  },
  {
    itemType: 'scenery_tree_pine',
    label: 'Pine Tree',
    emoji: '🌲',
    color: '#1B5E20',
    category: 'scenery',
    placeable: false,
    cols: 2,
    rows: 3,
    sortOrder: 111,
  },
  {
    itemType: 'scenery_tree_birch',
    label: 'Birch Tree',
    emoji: '🌿',
    color: '#81C784',
    category: 'scenery',
    placeable: false,
    cols: 2,
    rows: 3,
    sortOrder: 112,
  },
  {
    itemType: 'scenery_bush_large',
    label: 'Large Bush',
    emoji: '🌿',
    color: '#388E3C',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 120,
  },
  {
    itemType: 'scenery_bush_small',
    label: 'Small Bush',
    emoji: '☘️',
    color: '#4CAF50',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 121,
  },
  {
    itemType: 'scenery_rock_large',
    label: 'Large Rock',
    emoji: '🪨',
    color: '#757575',
    category: 'scenery',
    placeable: false,
    cols: 2,
    rows: 1,
    sortOrder: 130,
  },
  {
    itemType: 'scenery_rock_small',
    label: 'Small Rock',
    emoji: '🗿',
    color: '#9E9E9E',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 131,
  },
  {
    itemType: 'scenery_flowers',
    label: 'Wildflowers',
    emoji: '🌸',
    color: '#E91E63',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 140,
  },
  {
    itemType: 'scenery_mushroom',
    label: 'Mushrooms',
    emoji: '🍄',
    color: '#795548',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 141,
  },
  {
    itemType: 'scenery_stump',
    label: 'Tree Stump',
    emoji: '🪵',
    color: '#6D4C41',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 142,
  },

  // ── Assets (balloon visuals for spawns) ──────────────────────────────
  {
    itemType: 'floating_balloon_red',
    label: 'Red Balloon',
    emoji: '🎈',
    color: '#E53935',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 4,
    centerOverflow: true,
    sortOrder: 200,
  },
  {
    itemType: 'floating_balloon_blue',
    label: 'Blue Balloon',
    emoji: '🎈',
    color: '#1E88E5',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 4,
    centerOverflow: true,
    sortOrder: 201,
  },
  {
    itemType: 'floating_balloon_yellow',
    label: 'Yellow Balloon',
    emoji: '🎈',
    color: '#FDD835',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 4,
    centerOverflow: true,
    sortOrder: 202,
  },

  // ── Quest bubble icons (display-only, used above NPCs) ────────────────────
  {
    itemType: 'quest_lightbulb',
    label: 'Quest Available',
    emoji: '💡',
    color: '#FFD54F',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 210,
  },
  {
    itemType: 'quest_open_book',
    label: 'Quest In Progress',
    emoji: '📖',
    color: '#8D6E63',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 211,
  },
  {
    itemType: 'quest_closed_book',
    label: 'Quest Completable',
    emoji: '📕',
    color: '#5D4037',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 212,
  },
];

async function seed() {
  await connectDatabase();

  for (const item of ITEMS) {
    await GameItemDef.findOneAndUpdate(
      { itemType: item.itemType },
      { $set: item },
      { upsert: true, new: true },
    );
    console.log(`  Upserted: ${item.itemType}`);
  }

  console.log(`\nSeeded ${ITEMS.length} game item definitions.`);
  await disconnectDatabase();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
