import { connectDatabase, disconnectDatabase } from '../config/database.js';
import { GameItemDef } from '../models/GameItemDef.js';
import { copyTreeVariantArt, ensureCompoundTreeDefs } from '../services/TreeService.js';

const ITEMS = [
  // ── Buildings ────────────────────────────────────────────────────────
  {
    itemType: 'house',
    label: 'House',
    emoji: '🏠',
    color: '#D4A574',
    category: 'building',
    placeable: true,
    cols: 6,
    rows: 2,
    centerOverflow: true,
    interactAction: { type: 'open_scene', payload: 'house' },
    sortOrder: 1,
  },
  {
    itemType: 'cooking_pot',
    label: 'Cooking Pot',
    emoji: '🍳',
    color: '#8B7355',
    category: 'building',
    placeable: true,
    cols: 2,
    rows: 2,
    interactAction: { type: 'open_modal', payload: 'cooking' },
    sortOrder: 2,
  },
  {
    itemType: 'workbench',
    label: 'Workbench',
    emoji: '🔨',
    color: '#6D4C41',
    category: 'building',
    placeable: true,
    cols: 2,
    rows: 2,
    interactAction: { type: 'open_modal', payload: 'crafting' },
    buyable: true,
    gemPrice: 75,
    sortOrder: 3,
  },
  {
    itemType: 'smelter',
    label: 'Smelter',
    emoji: '🔥',
    color: '#C45C26',
    category: 'building',
    placeable: true,
    cols: 2,
    rows: 2,
    centerOverflow: true,
    interactAction: { type: 'open_modal', payload: 'smelting' },
    buyable: true,
    gemPrice: 120,
    sortOrder: 4,
  },
  {
    itemType: 'sell_box',
    label: 'Sell Box',
    emoji: '📦',
    color: '#8D6E63',
    category: 'building',
    placeable: true,
    cols: 2,
    rows: 2,
    interactAction: { type: 'open_modal', payload: 'sell_box' },
    sellable: false,
    sortOrder: 4,
  },
  {
    itemType: 'mail_box',
    label: 'Mailbox',
    emoji: '📬',
    color: '#5D4037',
    category: 'building',
    placeable: true,
    cols: 2,
    rows: 2,
    interactAction: { type: 'open_modal', payload: 'mail_box' },
    sellable: false,
    sortOrder: 5,
  },

  // ── Materials ────────────────────────────────────────────────────────
  {
    itemType: 'wood',
    label: 'Wood',
    emoji: '🪵',
    color: '#8D6E63',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    buyable: false,
    sortOrder: 12,
  },
  {
    itemType: 'stone',
    label: 'Stone',
    emoji: '🪨',
    color: '#9E9E9E',
    category: 'material',
    subCategory: 'ground_pickup',
    placeable: false,
    cols: 1,
    rows: 1,
    buyable: false,
    sortOrder: 13,
  },
  {
    itemType: 'iron_ore',
    label: 'Iron Ore',
    emoji: '⛏️',
    color: '#78909C',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 14,
  },
  {
    itemType: 'scrap',
    label: 'Scrap',
    emoji: '🗑️',
    color: '#607D8B',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 15,
  },
  {
    itemType: 'iron',
    label: 'Iron',
    emoji: '🔩',
    color: '#90A4AE',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    buyable: false,
    sortOrder: 16,
  },
  {
    itemType: 'cloth',
    label: 'Cloth',
    emoji: '🧵',
    color: '#E8D5C4',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    buyable: false,
    sortOrder: 17,
  },
  {
    itemType: 'glass',
    label: 'Glass',
    emoji: '🪟',
    color: '#B3E5FC',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    buyable: false,
    sortOrder: 18,
  },
  {
    itemType: 'rope',
    label: 'Rope',
    emoji: '🪢',
    color: '#C4A574',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    buyable: false,
    sortOrder: 19,
  },
  {
    itemType: 'crystal',
    label: 'Crystal',
    emoji: '💎',
    color: '#CE93D8',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    buyable: false,
    sortOrder: 20,
  },
  {
    itemType: 'wooden_plank',
    label: 'Plank',
    emoji: '📐',
    color: '#A1887F',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    buyable: false,
    sortOrder: 21,
  },

  // ── Soil ─────────────────────────────────────────────────────────────
  {
    itemType: 'soil',
    label: 'Soil',
    emoji: '🟫',
    color: '#8B5E3C',
    category: 'soil',
    placeable: true,
    cols: 6,
    rows: 5,
    sortOrder: 0,
  },

  // ── Seeds ────────────────────────────────────────────────────────────
  {
    itemType: 'wheat_seed',
    label: 'Wheat Seed',
    emoji: '🌱',
    color: '#A8D860',
    category: 'seed',
    placeable: true,
    cols: 1,
    rows: 1,
    growthMs: 30_000,
    harvestYield: [{ itemType: 'wheat', qty: 1 }],
    sellable: true,
    sellPrice: 1,
    sortOrder: 10,
  },

  // ── Ingredients ──────────────────────────────────────────────────────
  {
    itemType: 'wheat',
    label: 'Wheat',
    emoji: '🌾',
    color: '#E8D44D',
    category: 'ingredient',
    placeable: false,
    cols: 1,
    rows: 1,
    sellable: true,
    sellPrice: 3,
    sortOrder: 11,
  },

  // ── Fruit (subCategory for tree fruit) ───────────────────────────────
  {
    itemType: 'apple',
    label: 'Apple',
    emoji: '🍎',
    color: '#E53935',
    category: 'ingredient',
    subCategory: 'fruit',
    placeable: false,
    cols: 1,
    rows: 1,
    growsOnTrees: ['oak'],
    sortOrder: 11.5,
  },
  {
    itemType: 'dark_oak_nut',
    label: 'Dark Oak Nut',
    emoji: '🌰',
    color: '#5D4037',
    category: 'ingredient',
    subCategory: 'fruit',
    placeable: false,
    cols: 1,
    rows: 1,
    growsOnTrees: ['dark_oak'],
    sortOrder: 11.6,
  },

  // ── Trees (oak: apple, dark_oak: dark_oak_nut) ───────────────────────
  {
    itemType: 'tree_sappling_oak',
    label: 'Oak Sapling',
    emoji: '🌱',
    color: '#8BC34A',
    category: 'tree',
    placeable: true,
    cols: 1,
    rows: 1,
    harvestYield: [{ itemType: 'oak_wood', qty: 1 }],
    sortOrder: 25,
  },
  {
    itemType: 'tree_in_growth_oak',
    label: 'Oak Tree (Growing)',
    emoji: '🌳',
    color: '#558B2F',
    category: 'tree',
    placeable: true,
    cols: 2,
    rows: 2,
    harvestYield: [{ itemType: 'oak_wood', qty: 1 }],
    sortOrder: 26,
  },
  {
    itemType: 'tree_fully_grown_oak',
    label: 'Oak Tree',
    emoji: '🌳',
    color: '#2E7D32',
    category: 'tree',
    placeable: true,
    cols: 4,
    rows: 4,
    treeFruit: 'apple',
    harvestYield: [{ itemType: 'oak_wood', qty: 1 }],
    sortOrder: 27,
  },
  {
    itemType: 'tree_sappling_dark_oak',
    label: 'Dark Oak Sapling',
    emoji: '🌱',
    color: '#6D4C41',
    category: 'tree',
    placeable: true,
    cols: 1,
    rows: 1,
    harvestYield: [{ itemType: 'dark_oak_wood', qty: 1 }],
    sortOrder: 28,
  },
  {
    itemType: 'tree_in_growth_dark_oak',
    label: 'Dark Oak Tree (Growing)',
    emoji: '🌲',
    color: '#4E342E',
    category: 'tree',
    placeable: true,
    cols: 2,
    rows: 2,
    harvestYield: [{ itemType: 'dark_oak_wood', qty: 1 }],
    sortOrder: 29,
  },
  {
    itemType: 'tree_fully_grown_dark_oak',
    label: 'Dark Oak Tree',
    emoji: '🌲',
    color: '#3E2723',
    category: 'tree',
    placeable: true,
    cols: 4,
    rows: 4,
    treeFruit: 'dark_oak_nut',
    harvestYield: [{ itemType: 'dark_oak_wood', qty: 1 }],
    sortOrder: 30,
  },
  // Plain oak (no fruit, wood only) — for starter "normal" trees
  {
    itemType: 'tree_sappling_oak_plain',
    label: 'Oak Sapling',
    emoji: '🌱',
    color: '#8BC34A',
    category: 'tree',
    placeable: true,
    cols: 1,
    rows: 1,
    harvestYield: [{ itemType: 'oak_wood', qty: 1 }],
    sortOrder: 30.5,
  },
  {
    itemType: 'tree_in_growth_oak_plain',
    label: 'Oak Tree (Growing)',
    emoji: '🌳',
    color: '#558B2F',
    category: 'tree',
    placeable: true,
    cols: 2,
    rows: 2,
    harvestYield: [{ itemType: 'oak_wood', qty: 1 }],
    sortOrder: 30.6,
  },
  {
    itemType: 'tree_fully_grown_oak_plain',
    label: 'Oak Tree',
    emoji: '🌳',
    color: '#2E7D32',
    category: 'tree',
    placeable: true,
    cols: 4,
    rows: 4,
    harvestYield: [{ itemType: 'oak_wood', qty: 1 }],
    sortOrder: 30.7,
  },
  // Variant woods (from fully grown trees)
  {
    itemType: 'oak_wood',
    label: 'Oak Wood',
    emoji: '🪵',
    color: '#8D6E63',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 12.2,
  },
  {
    itemType: 'dark_oak_wood',
    label: 'Dark Oak Wood',
    emoji: '🪵',
    color: '#5D4E37',
    category: 'material',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 12.3,
  },
  {
    itemType: 'stick',
    label: 'Stick',
    emoji: '🪵',
    color: '#A1887F',
    category: 'material',
    subCategory: 'ground_pickup',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 12.5,
  },

  // ── Decorations ──────────────────────────────────────────────────────
  {
    itemType: 'fence',
    label: 'Fence',
    emoji: '🪵',
    color: '#C4A882',
    category: 'decoration',
    placeable: true,
    cols: 1,
    rows: 1,
    sortOrder: 20,
  },
  {
    itemType: 'rock',
    label: 'Rock',
    emoji: '🪨',
    color: '#9E9E9E',
    category: 'decoration',
    placeable: true,
    cols: 1,
    rows: 1,
    sortOrder: 21,
  },
  {
    itemType: 'pet_bed',
    label: 'Pet Bed',
    emoji: '🛏️',
    color: '#C4A882',
    category: 'decoration',
    subCategory: 'pet_bed',
    placeable: true,
    cols: 2,
    rows: 2,
    buyable: true,
    gemPrice: 50,
    sortOrder: 22,
  },
  {
    itemType: 'fossil_hole',
    label: 'Fossil Hole',
    emoji: '🕳️',
    color: '#6D4C41',
    category: 'decoration',
    subCategory: 'dig_hole',
    placeable: true,
    cols: 1,
    rows: 1,
    sortOrder: 24,
  },

  // ── Scenery (non-acquirable, admin-editable images) ──────────────
  {
    itemType: 'scenery_fence_h',
    label: 'Fence (Horizontal)',
    emoji: '🪵',
    color: '#A0845C',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 100,
  },
  {
    itemType: 'scenery_fence_v',
    label: 'Fence (Vertical)',
    emoji: '🪵',
    color: '#A0845C',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 101,
  },
  {
    itemType: 'scenery_fence_corner',
    label: 'Fence (Corner)',
    emoji: '🪵',
    color: '#A0845C',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 102,
  },
  {
    itemType: 'scenery_tree_oak',
    label: 'Oak Tree',
    emoji: '🌳',
    color: '#2E7D32',
    category: 'scenery',
    placeable: false,
    cols: 2,
    rows: 3,
    sortOrder: 110,
  },
  {
    itemType: 'scenery_tree_pine',
    label: 'Pine Tree',
    emoji: '🌲',
    color: '#1B5E20',
    category: 'scenery',
    placeable: false,
    cols: 2,
    rows: 3,
    sortOrder: 111,
  },
  {
    itemType: 'scenery_tree_birch',
    label: 'Birch Tree',
    emoji: '🌿',
    color: '#81C784',
    category: 'scenery',
    placeable: false,
    cols: 2,
    rows: 3,
    sortOrder: 112,
  },
  {
    itemType: 'scenery_bush_large',
    label: 'Large Bush',
    emoji: '🌿',
    color: '#388E3C',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 120,
  },
  {
    itemType: 'scenery_bush_small',
    label: 'Small Bush',
    emoji: '☘️',
    color: '#4CAF50',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 121,
  },
  {
    itemType: 'scenery_rock_large',
    label: 'Large Rock',
    emoji: '🪨',
    color: '#757575',
    category: 'scenery',
    placeable: false,
    cols: 2,
    rows: 1,
    sortOrder: 130,
  },
  {
    itemType: 'scenery_rock_small',
    label: 'Small Rock',
    emoji: '🗿',
    color: '#9E9E9E',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 131,
  },
  {
    itemType: 'scenery_flowers',
    label: 'Wildflowers',
    emoji: '🌸',
    color: '#E91E63',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 140,
  },
  {
    itemType: 'scenery_mushroom',
    label: 'Mushrooms',
    emoji: '🍄',
    color: '#795548',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 141,
  },
  {
    itemType: 'scenery_stump',
    label: 'Tree Stump',
    emoji: '🪵',
    color: '#6D4C41',
    category: 'scenery',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 142,
  },

  // ── Assets (balloon visuals for spawns) ──────────────────────────────
  {
    itemType: 'floating_balloon_red',
    label: 'Red Balloon',
    emoji: '🎈',
    color: '#E53935',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 4,
    centerOverflow: true,
    sortOrder: 200,
  },
  {
    itemType: 'floating_balloon_blue',
    label: 'Blue Balloon',
    emoji: '🎈',
    color: '#1E88E5',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 4,
    centerOverflow: true,
    sortOrder: 201,
  },
  {
    itemType: 'floating_balloon_yellow',
    label: 'Yellow Balloon',
    emoji: '🎈',
    color: '#FDD835',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 4,
    centerOverflow: true,
    sortOrder: 202,
  },

  // ── Quest bubble icons (display-only, used above NPCs) ────────────────────
  {
    itemType: 'quest_lightbulb',
    label: 'Quest Available',
    emoji: '💡',
    color: '#FFD54F',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 210,
  },
  {
    itemType: 'quest_open_book',
    label: 'Quest In Progress',
    emoji: '📖',
    color: '#8D6E63',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 211,
  },
  {
    itemType: 'quest_closed_book',
    label: 'Quest Completable',
    emoji: '📕',
    color: '#5D4037',
    category: 'asset',
    placeable: false,
    cols: 1,
    rows: 1,
    sortOrder: 212,
  },
];

async function seed() {
  await connectDatabase();

  for (const item of ITEMS) {
    await GameItemDef.findOneAndUpdate(
      { itemType: item.itemType },
      { $set: item },
      { upsert: true, new: true },
    );
    console.log(`  Upserted: ${item.itemType}`);
  }

  // oak_plain / dark_oak reuse oak sprites until they have their own art.
  await copyTreeVariantArt('oak', 'oak_plain');
  await copyTreeVariantArt('oak', 'dark_oak');

  for (const item of ITEMS) {
    const fruit = item as { itemType: string; growsOnTrees?: string[] };
    if (fruit.growsOnTrees?.length) {
      await ensureCompoundTreeDefs(fruit.itemType, fruit.growsOnTrees);
      console.log(`  Compound tree defs ensured for: ${fruit.itemType}`);
    }
  }

  console.log(`\nSeeded ${ITEMS.length} game item definitions.`);
  await disconnectDatabase();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
